# Info about you
name: Enrique Santibáñez-Cortés
position: Científico de datos
email: enriquesec@gmail.com
company_name: BBVA México, S.A.
company_url: https://www.bbva.mx/
place_name: Ciudad de México, MX

# Blog info
title: Enrique Santibáñez-Cortés
description: Blog
url: http://Enriquesec.github.io/

# Social links
github_url: https://github.com/Enriquesec
linkedin_url: http://www.linkedin.com/in/enrique-santibáñez-039044168
social:
  links:
    - http://www.linkedin.com/in/enrique-santibáñez-039044168
    - https://www.kaggle.com/enriquesec
    - https://github.com/Enriquesec

# Images + files
logo: /assets/img/heads.png
cv_url: /assets/files/Enriquesec_CV.pdf
resume_url: /assets/files/Enriquesec_CV.pdf

# Blog settings
markdown: kramdown

plugins: 
  - jekyll-seo-tag
highlighter: rouge
color_mode: auto  # auto, light, or dark
comments: true
disqus_shortname: enriquesec-github-io
syntax_highlight_stylesheet: syntax_highlight.css

# Colors - light mode
colors:
  text: 282828
  tag: dbefdc
  tag_hover: 93cf95
  header_background: 2b422b
  header_text: dbefdc
  header_link_hover: 93cf95
  links: 459c48
  links_visited: 357a38

# Colors - dark mode
colors_dark:
  background: 333
  text: ccc
  tag: 2e6830
  tag_hover: 93cf95
  header_background: 232
  header_text: 93cf95
  header_link: 93cf95
  header_link_hover: 459c48
  links: 459c48
  links_visited: 357a38